site_name: CyberDepot - Payload Repository
site_url: https://github.com/InfoSec-DB/CyberDepot
repo_url: https://github.com/InfoSec-DB/CyberDepot

nav:
  - CyberDepot: index.md
  - Payloads:
      - "Overview": payloads/index.md
      - "Web Exploits":
          - "XSS Attacks": payloads/web_exploits/xss.md
          - "SQL Injection": payloads/web_exploits/sql_injection.md
          - "CSRF Exploits": payloads/web_exploits/csrf.md
      - "Credential Attacks":
          - "Password Cracking": payloads/credential_attacks/password_cracking.md
          - "Credential Stuffing": payloads/credential_attacks/credential_stuffing.md
      - "Network Exploits":
          - "Botnets": payloads/network_exploits/botnets.md
          - "Reverse Shells": payloads/network_exploits/reverse_shells.md
      - "Search Engine Hacking":
          - "Google Dorks": payloads/search_engine_hacking/google_dorks.md
  - Reconnaissance:
      - "Overview": reconnaissance/index.md
      - "Tools":
          - "Shodan": reconnaissance/tools/shodan.md
          - "Nmap": reconnaissance/tools/nmap.md
      - "Cheatsheets":
          - "Shodan Cheatsheet": reconnaissance/cheatsheets/shodan_cheatsheet.md
  - Authentication Bypass:
      - "Overview": auth_bypass/index.md
      - "OTP Bypass Techniques": auth_bypass/otp_bypass.md
      - "Password Reset Poisoning": auth_bypass/password_reset_poisoning.md
      - "2FA Bypass via CSRF": auth_bypass/2fa_bypass_via_csrf.md
  - Vulnerability Disclosures:
      - "Overview": vuln_disclosures/index.md
      - "Boelter Blue System Management v1.3": vuln_disclosures/vuln_boelter_blue.md
  - WiFi Hacking:
      - "Overview": wifi_hacking/index.md
      - "WiFi Exploits": wifi_hacking/wifi_exploits.md
  - HTB Writeups:
      - "Overview": htb/index.md
      - "Starting Point":
          - "Overview": htb/starting_point/index.md
          - "Machines":
              - htb/starting_point/machine1.md
      - "Retired Machines":
          - "Overview": htb/retired_machines/index.md
          - "Machines":
              - htb/retired_machines/retired1.md






theme:
  name: material
  features:
    - navigation.sections  # Enables collapsible sidebar categories
    - navigation.prune  # Hides empty or invalid navigation items
    - navigation.indexes  # Makes category headers clickable if they have an index.md
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - navigation.instant
    - navigation.instant.progress
    - toc.follow
    - header.autohide
  language: en
  palette:
    - scheme: slate  # Use a dark scheme as the base
      primary: custom  # Bright red for primary actions and highlights
      accent: grey  # Grey for less prominent accents
  dark_mode: true  # Ensure that dark mode is the default
  font:
    text: "Roboto Mono"  # Monospaced font for that code-like feel
    code: "Fira Code"  # Excellent for showing code snippets with ligatures
  logo: "img/logo.svg"  # Custom logo for branding
  favicon: "img/favicon.ico"  # Custom favicon
  icon:
    repo: fontawesome/brands/github-alt
  titles_only: true
  include_homepage_in_sidebar: false
  include_sidebar: true

plugins:
  - search

extra_css:
  - css/custom.css  # Additional styles for customization

extra_javascript:
  - js/custom.js  # For any special interactive elements or fixes

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/InfoSec-DB
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/InfoSec-DB
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/InfoSec-DB

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

copyright: |
  &copy; 2023 <a href="https://github.com/InfoSec-DB/" target="_blank" rel="noopener">InfoSec-DB</a>
