site_name: CyberDepot - Payload Repository
site_url: https://github.com/InfoSec-DB/CyberDepot
repo_url: https://github.com/InfoSec-DB/CyberDepot

nav:
  - CyberDepot: index.md
  - Payloads:
      - "Explore Payloads": payloads/index.md
      - "XSS Payloads": payloads/xsspayloads.md
      - "Password Cracking": payloads/passcrack.md
      - "Google Dorks": payloads/googledorks.md
  - Reconnaissance:
      - "Shodan Guides": reconnaissance/shodan.md
      - "Nmap Cheat Sheet": reconnaissance/nmap.md
  - Authentication Bypass:
      - "OTP Bypass Techniques": auth_bypass/otpbypass.md
      - "Password Reset Poisoning": auth_bypass/passresetpoison.md
      - "2FA Bypass via CSRF": auth_bypass/2fabypasscsrf.md
  - Vulnerability Disclosures:
      - "Boelter Blue System Management v1.3": vuln_disclosures/vuln_boelter_blue.md
  - HTB Writeups:
      - "MonGod": htb/mongod.md

theme:
  name: material
  features:
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections  # Enables collapsible categories
    - navigation.expand  # Keeps top categories visible
    - navigation.prune
    - navigation.indexes  # Ensures category names are clickable
    - toc.follow
    - header.autohide
  language: en
  palette:
    - scheme: slate  # Dark mode
      primary: custom  # Bright red for highlights
      accent: grey  # Subtle contrast
  dark_mode: true
  font:
    text: "Roboto Mono"
    code: "Fira Code"
  logo: "img/logo.svg"
  favicon: "img/favicon.ico"
  icon:
    repo: fontawesome/brands/github-alt
  titles_only: true
  include_homepage_in_sidebar: false
  include_sidebar: true

plugins:
  - search

extra_css:
  - css/custom.css  # Custom styles

extra_javascript:
  - js/custom.js  # Custom scripts

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/InfoSec-DB
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/InfoSec-DB
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/InfoSec-DB

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

copyright: |
  &copy; 2025 <a href="https://github.com/InfoSec-DB/" target="_blank" rel="noopener">InfoSec-DB</a>
